<?
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
			
	$jmlSubKomponenList = count($this->subKomponenList);
	$subKomponenList['-'] = '--Pilih--';
	for ($i = 0; $i < $jmlSubKomponenList; $i++) {
		$subKomponenList[$this->subKomponenList[$i]->KodeSubKomponen] = (string)$this->subKomponenList[$i]->SubKomponen;			 
	}						
	if($jenisAksi == "Ubah"){							 
		$subKomponenAtrib = array("id"=>"KodeSubKomponen", "tabindex"=>"17", "onchange"=>"javascript:pilihSubKomponen();");							
	}else{
		$subKomponenAtrib = array("id"=>"KodeSubKomponen", "tabindex"=>"17", "onchange"=>"javascript:pilihSubKomponen();");
	}
	echo $ctrlFrm->formSelect('KodeSubKomponen', $this->kegiatanMenu['KodeSubKomponen'], $subKomponenAtrib, $subKomponenList);

?>