<?php
//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

$nama_file= "Laporan Data Indikator_".date('Y').".xls";
?>

<?php
	header("Content-type: application/octet-stream");
	header('Content-Disposition: attachment; filename="' . $nama_file . '"');
	header("Pragma: no-cache");
	header("Expires: 0");
?>


<h3 align ="center">Laporan Data Indikator Tahun <?php echo $this->tahun?></h3>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>Nama Indikator</th>
	  <th>Nama Kelurahan</th>
	  <th>Nilai Indikator</th>
	  <th>Tahun</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->nama_indikator);?></td>
		<td><?php echo $this->escape($data->Kelurahan);?></td>			
		<td><?php echo $this->escape($data->nilai_kelurahan);?></td>
		<td><?php echo $this->tahun?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
