<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array("01"=>'Januari',"02"=>'Februari',"03"=>'Maret', "04"=>'April', "05"=>'Mei',"06"=> 'Juni',"07"=>'Juli',"08"=>'Agustus',"09"=>'September',"10"=>'Oktober',"11"=> 'November',"12"=>'Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');

//echo "<h4>Cimahi, $tanggal</h4>";
$bulan=$array_bulan[$this->bulan];
?>


<?php
	$namafile="Laporan Data Indikator " . $this->tahun ." .xls";
	header("Content-type: application/octet-stream");
	header('Content-Disposition: attachment; filename="' . $namafile . '"');	
	header("Pragma: no-cache");
	header("Expires: 0");
?>


<h3 align ="center">Laporan Data Indikator Tahun <?php echo $this->tahun?></h3>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>Nama Indikator</th>
	  <th>Nama Kelurahan</th>
	  <th>Nilai Indikator</th>
	  <th>Tahun</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->nama_indikator);?></td>
		<td><?php echo $this->escape($data->Kelurahan);?></td>			
		<td><?php echo $this->escape($data->nilai_kelurahan);?></td>
		<td><?php echo $this->tahun?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>
<?php if (count($this->cetak) != 0){ ?>
	<a  href="<?php echo $this->basePath; ?>/indikator/indikator/cetaklaporandataindikator?id_indikator=<?echo $this->id_indikator;?>&kode_kelurahan=<?echo $this->kode_kelurahan;?>&tahun=<?echo $this->tahun;?>"><div class="download" title="cetak Data"></div> Download</a>
<?php } ?>
<span class="corners-bottom"><span></span></span>
<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
