<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "indikatormaxjs.phtml";
$referensi = Menu_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>

<div class="navlink">
<a href="#" class="home" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/home');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Indikator Maximum</h2>
		<div class="search-panel">
			<form method="post" id="frmPilihIndikatorMax" name="frmCariIndikatorMax"> Pilih Indikator :
				<?
					$jmlIndikatorMaxList = count($this->indikatorMaxList);
					$indikatorMaxList['-'] = '--Pilih--';
					for ($i = 0; $i < $jmlIndikatorMaxList; $i++) {
						$indikatorMaxList[$this->indikatorMaxList[$i]->id_indikator] = (string)$this->indikatorMaxList[$i]->kode_indikator | (string)$this->indikatorMaxList[$i]->nama_indikator;			 
					}
					
					$indikatorMaxAtrib = array("height"=>"10", "width"=>"10", "id"=>"id_indikator", "tabindex"=>"17", "onchange"=>"javascript:pilihIndikatorMax($this->jenisForm);");
					echo $ctrlFrm->formSelect('id_indikator', $this->indikatorMaxMenu['id_indikator'], $indikatorMaxAtrib, $indikatorMaxList);

				?>
			</form>
		</div>
		<div class="space-line"></div>		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			// $status = $this->hasil;
			// $proses = $this->proses;
			// $keterangan = $this->keterangan;
			
			// $pesan->show_message($proses, $keterangan, "$status" ); ?>
			// <div class="spacer"> </div>	
			// <div class="blank"></div>		
			
			// <?	
			// $totalData = $this->totIndikatorMax;
			// $modul = $this->basePath."/indikator/indikator/indikatormaxmenu";			
			// echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>