<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once "share/oa_dec_cur_conv.php";
require_once "indikatormaxjs.phtml";

$ctrlFrm = new Zend_View();
?>
<? if(strtolower($this->jenisForm) == 'form') {
		$namaForm = 'frmmaxindikator'; 
		$jenisAksi = 'Form';
	}
?>
		
<div class="navlink">
<a href="#" class="home" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/home');">Halaman Utama</a>
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title"><? echo $jenisAksi;?> Indikator Maksimum <br/> 
		<? echo $this->namaIndikator['kode_indikator'] ." . ". $this->namaIndikator['nama_indikator'] ?></h2>
	    <div class="spacer"></div> 	
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
				<input type="hidden" name="id_indikator" value="<?php echo $this->id_indikator; ?>"/>
				<tr>
				    <td align="right" width="180">Target 2015 :</td>
					<td>
						<?
						$TargetAttrib = array("size" => 100,"maxlength" => 100,"required"=>"true","title"=>"Target 2015 harus diisi");
						echo $ctrlFrm->formText('target', $this->dataIndikatorMaxTarget['target'], $TargetAttrib);
						?>						
					</td>
					<td>&nbsp;&nbsp;</td>
					<td align="right" width="180">Jawa Barat :</td>
					<td>
						<?
						$JabarAttrib = array("size" => 100,"maxlength" => 100,"required"=>"true","title"=>"Target Jawa Barat harus diisi");
						echo $ctrlFrm->formText('jawa_barat', $this->dataIndikatorMaxTarget['jawa_barat'], $JabarAttrib);
						?>						
					</td>
				</tr>
				<tr>
				    <td align="right" width="180">Nasional :</td>
					<td>
						<?
						$NasionalAttrib = array("size" => 100,"maxlength" => 100,"required"=>"true","title"=>"Target Nasional harus diisi");
						echo $ctrlFrm->formText('nasional', $this->dataIndikatorMaxTarget['nasional'], $NasionalAttrib);
						?>						
					</td>
					<td>&nbsp;&nbsp;</td>
					<td align="right" width="180">Cimahi :</td>
					<td>
						<?
						$CimahiAttrib = array("size" => 100,"maxlength" => 100,"required"=>"true","title"=>"Target Cimahi harus diisi");
						echo $ctrlFrm->formText('cimahi', $this->dataIndikatorMaxTarget['cimahi'], $CimahiAttrib);
						?>						
					</td>
				</tr>			
			</table>
			
			<table id="sorter" class="sortable" cellspacing="0" cellpadding="2" border="0" align="center">
				<th width=3%  class="nosort">No</th> 
				<th width=5% class="sorted order2 sortable">Kelurahan</th> 
				<th width=5% class="sorted order2 sortable">Nilai Kelurahan</th>
				
				<? $i = 1;
				foreach ($this->dataIndikatorMaxKelurahan as $key => $val): 					
					$id_indikator = $this->escape($val['id_indikator']); 
					$Kelurahan = $this->escape($val['Kelurahan']); 
					$nilai_kelurahan = $this->escape($val['nilai_kelurahan']); 
					$id_form_isian_kelurahan = $this->escape($val['id_form_isian_kelurahan']); 
					$kategori = $this->escape($val['kategori']); 
				?>
				
				<tr>
					<input type="hidden" name="form_isian_kelurahan[]" value="<?php echo $i; ?>">
					<input type="hidden" name="kategori_<?php echo $i; ?>" value="<?php echo $kategori ?>">
					<td class="clleft"><? echo $i ?></td>
					<td class="clcenter"><? echo $Kelurahan ?>
					<td><input type="text" name="nilai_kelurahan_<?php echo $i; ?>" value="<? echo $nilai_kelurahan ?>" id="nilai_kelurahan" required title="Nilai Kelurahan Harus diisi"></td>
				</tr>
				
				<? $i++;
				endforeach; ?>
				<tr>
				    <td></td>
				    <td>
						<div class="right">
							<input type="button" value="Batal" onClick="kotaMenu();"> 
							<input type="reset" value="Ulangi"> 
							<input type="submit" value="Simpan">
						</div>
					</td>
				</tr>
				
			</table>
		</form>
	</div>
</div>