<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "indikatormaxjs.phtml";
$referensi = Menu_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Google Maps KML</title>
    <meta name="description" content="menampilkan polygon dari kml di googlemaps">
    <meta name="author" content="El Cicko">
	<style type="text/css">
		body{ font: 62.5% "Trebuchet MS", sans-serif; margin: 50px;}
	</style>	
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<!-- memanggil library geoxml3 untuk parsing data kml ke peta -->
	<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.js"></script>
	<script type="text/javascript" src="<? echo $this->basePath;?>/js/geoxml3.js"></script>
	<script type="text/javascript">
	var peta;
	function peta_awal(){
		var jawa_barat = new google.maps.LatLng(-6.870698, 107.555116);
		var petaoption = {
			zoom: 12,
			center: jawa_barat,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};

		peta = new google.maps.Map(document.getElementById("petaku"),petaoption);
		/** disini kita panggil function dari geoXML3 untuk memparsing file kml */
		var geoXml = new geoXML3.parser({map: peta});
		/** letak file kml */
		geoXml.parse('<? echo $this->basePath;?>/js/cimahi.kml');
		google.maps.event.addListener(peta,'click',function(event){
			kasihtanda(event.latLng);
		});
	}
	</script>
	</head>
	<fieldset class="fields1" >	
		<input type="button" onclick="window.close()" value="Tutup"/>
	</fieldset>
	<body onload="peta_awal()">
		<h2>Google Maps KML</h2>
		<div id="petaku" style="height:500px"></div>
	</body>
</html>

