<script type="text/javascript">

function pilihIndikatorMax(jenisForm)
{
	id_indikator = document.getElementById('id_indikator').value;
	//jenisForm = document.getElementById('jenisForm').value;
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxolahdata';
	var param = {id_indikator:id_indikator,jenisForm:jenisForm};
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function indikatorMaxMenu()
{
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxmenu';
	jQuery.get(url, function(data) {
		$("div#tableview").html(data);
	});
}

function indikatorForm(jenisForm, id_indikator)
{
	
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxolahdata';
	
	var param = { jenisForm:jenisForm, id_indikator:id_indikator};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahindikatormax").ajaxForm(tambahIndikatorMax_opt);
		jQuery("#frmubahindikatormax").ajaxForm(ubahIndikatorMax_opt);		
		});
	
}

function cariIndikatorMax(){
	$("#frmCariIndikatorMax").ajaxForm(frmCariIndikatorMax_opt);
}

var frmCariIndikatorMax_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxmenu',
		type: 'post', 
		resetForm: false
};


function Popup(id_indikator){
	url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxgrafik?id_indikator=' + id_indikator;
	var param = {id_indikator:id_indikator};
	BukaWindows();
}

function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 1100, popH = 500;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function FormMax(jenisForm, id_indikator)
{
	
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxform';
	
	var param = { jenisForm:jenisForm, id_indikator:id_indikator};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmmaxindikator").ajaxForm(formMaxIndikator_opt);		
		});	
}


var formMaxIndikator_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxform',
		type: 'post', 
		resetForm: false
};

// var ubahKota_opt = {
	// target : '#tableview',
	// url: '<?php echo $this->basePath; ?>/kota/kota/simpankotaedit',
	// beforeSubmit : function() {
		// if (document.getElementById('kode_kota').value == ''){
			// alert('Kode Kota harus Diisi');
			// return false;
		// }
		// if (document.getElementById('kota').value == ''){
			// // alert('Nama Kota harus Diisi');
			// return false;
		// }
	// },
	// success: function(){doCount(5);},
	// type: 'post', 
	// resetForm: false
// };

// function Kotahapus(param1, param2)
// { 
	
	// if(ConfirmDelete(param1, param2))
	// {	//alert("test");
		// handler = '<?php echo $this->basePath; ?>/kota/kota/kotahapus';
		// var opt = {kode_kota : param2};
		// jQuery.get(handler,opt,function(data) {
				// $("#tableview").html(data);
				// doCount(5);
			 // });
	// }
// }  
</script>