<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "indikatorminjs.phtml";
$referensi = Menu_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>


<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Grafik Indikator Maksimum</title>
<link href="<? echo $this->basePath;?>/css/tools.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/thickbox.css" type="text/css" media="screen" />
<link href="<? echo $this->basePath;?>/css/main.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/style.css" type="text/css" title="Nice Blue style" />
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.js" type="text/javascript"></SCRIPT>
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.form.js" type="text/javascript"></SCRIPT>
<script src="<? echo $this->basePath;?>/js/jquery.min.js" type="text/javascript"></script>


<script type="text/javascript" src="<? echo $this->basePath;?>/js/exporting.js" ></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/js/highcharts.js" ></script>

<script type="text/javascript">
var chart1; // globally available
$(document).ready(function() {
      chart1 = new Highcharts.Chart({
         chart: {
            renderTo: 'container',
            type: 'column'
         },   
         title: {
            text: 'Hasil'
         },
         xAxis: {
            categories: ['Kelurahan']
         },
         yAxis: {
            title: {
               text: 'Nilai Kelurahan'
            }
         },
		 legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
              series:             
        [
            <?php 
			foreach ($this->grafik as $key => $val): 
				$Kelurahan = $this->escape($val['Kelurahan']); 
				$hasil = $this->escape($val['hasil']); 
				$nilai_kelurahan = $this->escape($val['nilai_kelurahan']); 			
				$warna_indikator = $this->escape($val['warna_indikator']);
			?>
				 {
                      name: '<?php echo $Kelurahan; ?>',
                      data: [<?php echo $nilai_kelurahan; ?>],
					  
					  <? if($warna_indikator == 1){ //hijau
						?>
						color:  '#00B300'
					<?}else if($warna_indikator == 2){ //kuning
						?>
						color: '#FFFF00'
					<? }else if($warna_indikator == 3){ //merah
						?>
						color: '#FF0000'
					<? } ?>
                 },
			<?	endforeach; ?>
        ]
      });
   });	
</script>
<style>
	.merah {				
		background: #FF0000 !important;
	
		color: #424251;
	}
	
	.kuning {				
		background: #FFFF00 !important;
	
		color: #424251;
	}
	
	.hijau {				
		background: #00B300 !important;
	
		color: #424251;
		
	}
	
	.lama {
		font-size: 15px;
	}			
</style>
</head>

<body>	
	<div class="popups" >
	<div class="space-line"></div>
	<div id="tableview">
	<div class="blank"></div>
	
	<fieldset class="fields">
		<div id='container'></div>		
	</fieldset>
	Keterangan:
	<table>
	<tr>
		<td width="30px;"><div class="hijau">&nbsp;</td>
		<td>&nbsp;:&nbsp;</td>
		<td>Telah mencapai target</td>
	</tr>
	<tr>
		<td width="30px;"><div class="kuning">&nbsp;</td>
		<td>&nbsp;:&nbsp;</td>
		<td>Dalam arah pencapaian</td>
	</tr>
	<tr>
		<td width="30px;"><div class="merah">&nbsp;</td>
		<td>&nbsp;:&nbsp;</td>
		<td>Jauh dari arah pencapaian</td>
	</tr>
  </table>
	<fieldset class="fields1" >	
		<input type="button" onclick="window.close()" value="Tutup"/>
	</fieldset>
	</div>
	</div>
</body>
</html>