<script type="text/javascript">
function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

//----------------------------------------MAXIMUM
function pilihIndikatorMax(jenisForm)
{
	id_indikator = document.getElementById('id_indikator').value;
	//jenisForm = document.getElementById('jenisForm').value;
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxolahdata';
	var param = {id_indikator:id_indikator,jenisForm:jenisForm};
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function indikatorMaxMenu()
{
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormaxmenu';
	jQuery.get(url, function(data) {
		$("div#tableview").html(data);
	});
}

//-------------------------------------------INDIKATOR AJA
function cariIndikator(){
	$("#frmCariIndikator").ajaxForm(frmCariIndikator_opt);
}

var frmCariIndikator_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/indikator/indikator/indikatormenu',
		type: 'post', 
		resetForm: false
};

function indikatorForm(jenisForm, id_indikator)
{
	
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatorolahdata';
	
	var param = { jenisForm:jenisForm, id_indikator:id_indikator};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahindikator").ajaxForm(tambahIndikator_opt);
		jQuery("#frmubahindikator").ajaxForm(ubahIndikator_opt);		
		});	
}

function pilihGoal(jenisForm)
{
	id_goal = document.getElementById('id_goal').value;
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatorolahdata';
	var param = {id_goal:id_goal,jenisForm:jenisForm};
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function goalMenu()
{
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatormenu';
	jQuery.get(url, function(data) {
		$("div#tableview").html(data);
	});
}

function pilihKategori(jenisForm)
{
	id_kategori = document.getElementById('id_kategori').value;
	var url = '<?php echo $this->basePath; ?>/indikator/indikator/indikatorolahdata';
	var param = {id_kategori:id_kategori,jenisForm:jenisForm};
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

var tambahIndikator_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/indikator/indikator/simpanindikator',
	beforeSubmit : function() {
		if (document.getElementById('id_goal').value == ''){
			alert('Goal harus dipilih');
			return false;
		}
		if (document.getElementById('kode_indikator').value == ''){
			alert('Kode Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('nama_indikator').value == ''){
			alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('definisi').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('manfaat').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('sumber_data').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('nilai_target').value == ''){
			alert('Nilai Target harus Diisi');
			return false;
		}
		if (document.getElementById('kategori').value == ''){
			alert('Kategori harus dipilih');
			return false;
		}
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

var ubahIndikator_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/indikator/indikator/simpanindikatoredit',
	beforeSubmit : function() {
		if (document.getElementById('id_goal').value == ''){
			alert('Goal harus dipilih');
			return false;
		}
		if (document.getElementById('kode_indikator').value == ''){
			alert('Kode Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('nama_indikator').value == ''){
			alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('definisi').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('manfaat').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('sumber_data').value == ''){
			//alert('Nama Indikator harus Diisi');
			return false;
		}
		if (document.getElementById('nilai_target').value == ''){
			alert('Nilai Target harus Diisi');
			return false;
		}
		if (document.getElementById('kategori').value == ''){
			alert('Kategori harus dipilih');
			return false;
		}
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

function indikatorHapus(param1, param2)
{ 
	
	if(ConfirmDelete(param1, param2))
	{	
		handler = '<?php echo $this->basePath; ?>/indikator/indikator/indikatorhapus';
		var opt = {id_indikator : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}  

//cetak data laporan indikator
function cetakLaporanDataIndikator(){
	$("#cetaklaporandataindikator").ajaxForm(cetaklaporandataindikator_opt);
}

var cetaklaporandataindikator_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/indikator/indikator/cetaklaporandataindikator',
		type: 'post', 
		resetForm: false
};



</script>